services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/bovann?retryWrites=true&w=majority
      - JWT_SECRET=bovann_jwt_secret_2025
      - NODE_ENV=production
    depends_on:
      - mongo
      - mongo-setup
    restart: unless-stopped

  mongo:
    image: mongo:6
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-setup:
    image: mongo:6
    depends_on:
      - mongo
    restart: on-failure
    command: >
      bash -c "
        sleep 10 &&
        until mongosh --host mongo:27017 --eval 'rs.status()' >/dev/null 2>&1; do
          echo 'En attente de MongoDB...'
          sleep 2
        done &&
        mongosh --host mongo:27017 --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongo:27017\"}]})' &&
        echo 'Replica set initialisé'
      "

volumes:
  mongo_data: